apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
    app: my-backend  # ADD THIS LINE - critical for ServiceMonitor matching
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '3000'
    prometheus.io/scrape: 'true' 
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}